site:
  title: Culture générale
  url: https://dhrions.github.io/general-knowledge

content:
  branches: antora
  sources:
  - url: ..
    start_path: content

ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

output:
  dir: ./build
